// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $api_gamestate from "./routes/api/gamestate.ts";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $Alchemy from "./islands/Alchemy.tsx";
import * as $DiscordButton from "./islands/DiscordButton.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $ThemeToggle from "./islands/ThemeToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/api/gamestate.ts": $api_gamestate,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
  },
  islands: {
    "./islands/Alchemy.tsx": $Alchemy,
    "./islands/DiscordButton.tsx": $DiscordButton,
    "./islands/Login.tsx": $Login,
    "./islands/ThemeToggle.tsx": $ThemeToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
